#define PRINT_DEBUG_INFORMATION

#define DEFAULT_PRECISION 256
#define DEFAULT_ANGLE_MODE RAD
#define MAX_INPUT_LENGTH 1024

#define COLOR_BACKGROUND 0x000000 // Black
#define COLOR_TEXT 0xFFFFFF       // White
#define COLOR_ACCENT 0xFF0000     // Red
#define SCREEN_BRIGHTNESS 128     // 0-255 range

#ifdef PRINT_DEBUG_INFORMATION
#include <iostream>
#endif